### ISSUE TITLE
I can't add merge script to aegisub

### ISSUE THREAD

**Issue by abdullahal25** [TypesettingTools/Myaamori-Aegisub-Scripts#11]
I feel so noob now.. I tried to use merge script by adding it from automotion menu but it shows error
I couldn't add any of your .moon scripts so I think that I am not doing it in a right way
Looking forward for some help about how to use it and thanks
I am using Aegisub 3.2.2 btw 

![Capture](https://user-images.githubusercontent.com/46882070/99762650-a9489500-2b01-11eb-80be-df43e10c52cc.PNG)

**Comment by Myaamori** [comment]
You probably need a newer version of Aegisub. Make sure you also have Dependency Control installed. The builds at https://thevacuumof.space/builds/ come with Dependency Control; alternatively get either https://github.com/wangqr/Aegisub/releases or https://github.com/Ristellise/AegisubDC/releases and install Dependency Control from https://github.com/TypesettingTools/DependencyControl/releases.

**Comment by Myaamori** [comment]
I'll close this issue, but feel free to reopen it if you're still having issues after upgrading to a newer build of Aegisub.

**Comment by abdullahal25** [comment]
@Myaamori 
Thanks alot Myaamori.. It works fine now 
love your efforts, btw
