### ISSUE TITLE
How to use "Apply karaoke template" like in Automation Aegisub with Sub Digest?

### ISSUE THREAD

**Issue by tknightz** [TypesettingTools/Myaamori-Aegisub-Scripts#12]
I wanna merge 2 ass files: 
1. template.ass (styles, effects,..) 
2. sub.ass (that file I want to apply style and effects from template.ass). 

I've tried to use` --merge-file` option but it's not "apply" the karaoke effect of `template.ass` to `sub.ass`

Is there any options to do it with Sub Digest?
Thanks for your amazing works.

**Comment by FichteFoll** [comment]
If you mean to run the karaoke templater on `template.ass`, you want https://github.com/Myaamori/SubKt instead.

**Comment by tknightz** [comment]
> If you mean to run the karaoke templater on `template.ass`, you want https://github.com/Myaamori/SubKt instead.
Thank you! I've figured out that `aegisub-cli `could solve my problem.
