### ISSUE TITLE
Fontvalidator can not find font with special character

### ISSUE THREAD

**Issue by moi15moi** [TypesettingTools/Myaamori-Aegisub-Scripts#19]
Fontvalidator can not find font with special character.

Here is an example:
![image](https://user-images.githubusercontent.com/80980684/162646721-09a876a8-7527-482b-8959-75fdbbd6fe94.png)

Ass file: https://mega.nz/file/SxdA0RyI#0s-RTJlfyxns8r3hePgPawBFwOwV46_PYT5webvj0T4
Font file: https://mega.nz/file/S9ERDRpQ#bcPhS06kv-D5jt64aTNDbZVd6gZr6ZfJDYT91yYsoWk

**Comment by anne-o-pixel** [comment]
On my Linux OS, the font name provided above is not `Fjイーマ310` but `FjÉCÅ[É}310` :/

Edit: weird, using assfc, it's working

**Comment by moi15moi** [comment]
assfc does not use fonttools which is the problem.

**Comment by moi15moi** [comment]
> On my Linux OS, the font name provided above is not `Fjイーマ310` but `FjÉCÅ[É}310` :/
> 
> Edit: weird, using assfc, it's working

I tested with assfc. I have the same problem..

**Comment by moi15moi** [comment]
I informed my self.

The problem is not from FontValidator. It seems to be from fontTools.
