### ISSUE TITLE
Merge Scripts: Wildcard Matching

### ISSUE THREAD

**Issue by Funami580** [TypesettingTools/Myaamori-Aegisub-Scripts#9]
How about adding support for wildcard matching? It may be useful if you have for every typeset one file and you don't want to import every file by hand.

For example importing all files in a directory:
```
typesetting/*
typesetting/*.ass
```

Or files with a specific name:
```
typesetting.*.ass
*.typesetting.ass
```
<br>
Kind regards

**Comment by Myaamori** [comment]
Added in version 0.0.13. It required a bit of refactoring, so hopefully I didn't break something along the way, though everything seemed to work based on my testing. Let me know if you run into any issues.
